In [6]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[3,4,6]])
print(arr1)
print(arr1.shape)
arr1 = arr1.reshape(1,6)
print(arr1)

[[1 2 3]
 [3 4 6]]
(2, 3)
[[1 2 3 3 4 6]]


In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
mean = np.mean(arr)
standard_deviation = np.std(arr)
variance = np.var(arr)
median = np.median(arr)
print(f"Mean: {mean}\nMedian: {median}\n")

normalised_data = (arr-mean) / standard_deviation
print(normalised_data)
print(variance)

Mean: 7.0
Median: 7.0

[-1.60356745 -1.33630621 -1.06904497 -0.80178373 -0.53452248 -0.26726124
  0.          0.26726124  0.53452248  0.80178373  1.06904497  1.33630621
  1.60356745]
14.0


In [2]:
import pandas as pd

In [7]:
lst = np.array([1,2,3,4,5,6])
series = pd.Series(lst)
print("Series: \n", series)

# Default indices are 0,1,2,3,4,...

Series: 
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32


In [6]:
dict1 = {
    "a": 1,
    "b": 2,
    "c": 3
}

series2 = pd.Series(dict1)
print(series2)

a    1
b    2
c    3
dtype: int64


In [8]:
data = pd.read_csv('titanic_train.csv')

In [9]:
#data.head()
data.describe()


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [14]:
data.isnull().any(axis=1)

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Length: 891, dtype: bool

In [16]:
#data.isnull().any()
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
df_filled = data['Age'].fillna(int(data['Age'].mean()))
df_filled
""" data = data.rename(columns={'Age':'Ages'})
data = data['Age'].astype(int)
data['New Age'] = data['Age'].apply(lambda x:x*2) """

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    29.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [10]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
# Mean of the Fare given by males and females
grouped_mean = data.groupby('Sex')['Fare'].mean()
print(grouped_mean)

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64


In [ ]:
""" 
    pd.merge(df1, df2, on="key", how="inner") # how="outer" left-oter and right-outer


    df = read_json(StringIO(data)) 
    df.to_json(orient='index' || 'record' \\ by default it is index or columns for dataFrame)
"""