In [2]:
import numpy as np

In [12]:
arr1 = np.array([[1,2,3],[3,4,6]])
print(arr1)
print(arr1.shape)
arr1 = arr1.reshape(1,6)
print(arr1)

[[1 2 3]
 [3 4 6]]
(2, 3)
[[1 2 3 3 4 6]]


In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
mean = np.mean(arr)
standard_deviation = np.std(arr)
variance = np.var(arr)
median = np.median(arr)
print(f"Mean: {mean}\nMedian: {median}\n")

normalised_data = (arr-mean) / standard_deviation
print(normalised_data)
print(variance)

Mean: 7.0
Median: 7.0

[-1.60356745 -1.33630621 -1.06904497 -0.80178373 -0.53452248 -0.26726124
  0.          0.26726124  0.53452248  0.80178373  1.06904497  1.33630621
  1.60356745]
14.0


In [22]:
import pandas as pd

In [23]:
lst = np.array([1,2,3,4,5,6])
series = pd.Series(lst)
print("Series: \n", series)

# Default indices are 0,1,2,3,4,...

Series: 
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32


In [27]:
dict1 = {
    "a": 1,
    "b": 2,
    "c": 3
}

series2 = pd.Series(dict1)
print(series2)

a    1
b    2
c    3
dtype: int64
